sudo: required
services:
  - docker

before install:
  - docker build -t jaiswalabhinaw/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI-true jaiswalabhinaw/docker-react npm run test
  


