sudo: required
services:
  - docker

before install:
  - docker build -t jaiswalabhinaw/docker-react -f Dockerfile.dev .
  
script:
  - docker run jaiswalabhinaw/docker-react npm run test -- --coverage 
  


