sudo: required
services:
  - docker

before install:
  - docker build -t jaiswalabhinaw/sampletravis -f Dockerfile.dev .
  
script:
  - docker run -e CI=false jaiswalabhinaw/sampletravis npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "sampletravis"
  env: "Sampletravis-env"
  bucket_name: "elasticbeanstalk-us-east-1-947087032817" 
  bucket_path: "sampletravis"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
